{% set name = "mkdocs-table-reader-plugin" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb15688ee8c0cd1a842f506f18973b87be22bd7baa5e2e551089de6b7f9ec25b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.0
    - pandas >=1.1
    - tabulate >=0.8.7
    - PyYAML >=5.4.1

test:
  imports:
    - mkdocs_table_reader_plugin
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://timvink.github.io/mkdocs-table-reader-plugin/#documentation
  summary: MkDocs plugin to directly insert tables from files into markdown.
  description: MkDocs plugin to directly insert tables from files into markdown.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://timvink.github.io/mkdocs-table-reader-plugin/#documentation
  dev_url: https://github.com/timvink/mkdocs-table-reader-plugin

extra:
  recipe-maintainers:
    - cpcloud
